### PR TITLE
UI design and implementation for the project.

### PR DESCRIPTION
**Pull request by rnjane**
What the PR does.
- Check on the UI design of the project, without code implementation.

Task Description.
- Create a wireframe design of the project UI.
- Implement the design made using HTML and CSS.

How to test manually.
- Clone the repository https://github.com/rnjane/bucket-list-app
- Open the folder UI, and run the HTML pages on your browser.

### CODE REVIEW

**Comment by JayKay24** [comment]
Informative README.md file. Include coverage reporting and travis CI badges

**Comment by dreamerTram** [comment]
Your PR has no summary of what the code to be integrated is set to achieve

**Comment by jmnyarega** [comment]
Good readme , make your PR descriptive

**Comment by rnjane** [comment]
@dreamerTram @jmnyarega I have updated my PR summary. Can I get a review for my new one?

**Pull request merged**
